export const GAME_WIDTH = 1024
export const GAME_HEIGHT = 600
export const SHIP_SPEED = 7
export const FIRE_RATE = 150

const iconWeapon = `<svg viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="1" stroke-linejoin="round" class="w-full h-full"><path d="M12 2L15 10H22L16 15L18 22L12 17L6 22L8 15L2 10H9L12 2Z"/></svg>`

export const WEAPON_TYPES = [
  {
    id: 0,
    name: 'Ion Laser',
    icon: iconWeapon,
    color: 'text-yellow-400 drop-shadow-[0_0_5px_currentColor]',
    speed: 25,
    size: 6,
    type: 'yellow',
    shape: 'beam',
  },
  {
    id: 1,
    name: 'Laser',
    icon: iconWeapon,
    color: 'text-cyan-400 drop-shadow-[0_0_5px_currentColor]',
    speed: 20,
    size: 4,
    type: 'blue',
    shape: 'dash',
  },
  {
    id: 2,
    name: 'Plasma',
    icon: iconWeapon,
    color: 'text-red-500 drop-shadow-[0_0_5px_currentColor]',
    speed: 12,
    size: 10,
    type: 'red',
    shape: 'plasma-fan',
  },
  {
    id: 3,
    name: 'Energy Wave',
    icon: iconWeapon,
    color: 'text-green-400 drop-shadow-[0_0_5px_currentColor]',
    speed: 20,
    size: 12,
    type: 'green',
    shape: 'wave',
  },
  {
    id: 4,
    name: 'Neutron',
    icon: iconWeapon,
    color: 'text-purple-500 drop-shadow-[0_0_5px_currentColor]',
    speed: 25,
    size: 6,
    type: 'purple',
    shape: 'needle',
  },
  {
    id: 5,
    name: 'Lightning',
    icon: iconWeapon,
    color: 'text-blue-300 drop-shadow-[0_0_5px_currentColor]',
    speed: 22,
    size: 24,
    type: 'lightning',
    shape: 'bolt',
  },
  {
    id: 6,
    name: 'Wavy Beam',
    icon: iconWeapon,
    color: 'text-pink-500 drop-shadow-[0_0_5px_currentColor]',
    speed: 40,
    size: 40,
    type: 'pink',
    shape: 'wavy-beam',
  },
  {
    id: 7,
    name: 'Acid Glob',
    icon: iconWeapon,
    color: 'text-lime-500 drop-shadow-[0_0_5px_currentColor]',
    speed: 10,
    size: 14,
    type: 'lime',
    shape: 'blob',
  },
  {
    id: 8,
    name: 'Magma Shard',
    icon: iconWeapon,
    color: 'text-orange-600 drop-shadow-[0_0_5px_currentColor]',
    speed: 18,
    size: 12,
    type: 'orange',
    shape: 'shard',
  },
  {
    id: 9,
    name: 'Shotgun',
    icon: iconWeapon,
    color: 'text-gray-300 drop-shadow-[0_0_5px_currentColor]',
    speed: 24,
    size: 8,
    type: 'gray',
    shape: 'pellet',
  },
]
